
gpt_queries_hard ="""
```
Example queries set (hard difficulty) that should require nested queries.

1. "Find funds whose total assets exceed the average total assets of all funds."
WITH AvgAssets AS (
    SELECT AVG(TOTAL_ASSETS) AS AVG_TOTAL_ASSETS
    FROM FUND_REPORTED_INFO
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_ASSETS > (SELECT AVG_TOTAL_ASSETS FROM AvgAssets);

2. "List the top 5 registrants by fund count, excluding those with below-average counts."
WITH AvgFundCount AS (
    SELECT AVG(FUND_COUNT) AS AVG_COUNT
    FROM (SELECT REGISTRANT_NAME, COUNT(*) AS FUND_COUNT FROM REGISTRANT R
          JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
          GROUP BY REGISTRANT_NAME) Subquery
)
SELECT REGISTRANT_NAME, COUNT(*)
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
GROUP BY REGISTRANT_NAME
HAVING COUNT(*) > (SELECT AVG_COUNT FROM AvgFundCount)
ORDER BY COUNT(*) DESC
LIMIT 5;

3. "Show funds whose liabilities are more than twice the average liability of all funds."
WITH AvgLiabilities AS (
    SELECT AVG(TOTAL_LIABILITIES) AS AVG_LIABILITY
    FROM FUND_REPORTED_INFO
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_LIABILITIES AS FLOAT > 2 * (SELECT AVG_LIABILITY FROM AvgLiabilities);

4. "Identify registrants whose states have the most funds."
WITH StateFundCount AS (
    SELECT STATE, COUNT(*) AS FUND_COUNT
    FROM REGISTRANT
    GROUP BY STATE
)
SELECT REGISTRANT_NAME
FROM REGISTRANT
WHERE STATE = (SELECT STATE FROM StateFundCount ORDER BY FUND_COUNT DESC LIMIT 1);

5. "Find funds whose total assets match the maximum total assets of their registrant's state."
WITH StateMaxAssets AS (
    SELECT STATE, MAX(TOTAL_ASSETS) AS MAX_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY STATE
)
SELECT SERIES_NAME, STATE
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE TOTAL_ASSETS = (SELECT MAX_ASSETS FROM StateMaxAssets WHERE STATE = R.STATE);

6. "List the registrants whose funds account for more than 5% of total reported assets."
WITH TotalAssets AS (
    SELECT SUM(TOTAL_ASSETS) AS GLOBAL_TOTAL
    FROM FUND_REPORTED_INFO
)
SELECT REGISTRANT_NAME, SUM(F.TOTAL_ASSETS)
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
GROUP BY REGISTRANT_NAME
HAVING SUM(F.TOTAL_ASSETS) > 0.05 * (SELECT GLOBAL_TOTAL FROM TotalAssets);

7. "Find the largest fund for each registrant."
WITH LargestFunds AS (
    SELECT REGISTRANT_NAME, MAX(TOTAL_ASSETS) AS MAX_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
)
SELECT REGISTRANT_NAME, SERIES_NAME
FROM FUND_REPORTED_INFO F
JOIN REGISTRANT R ON F.ACCESSION_NUMBER = R.ACCESSION_NUMBER
WHERE TOTAL_ASSETS = (SELECT MAX_ASSETS FROM LargestFunds WHERE REGISTRANT_NAME = R.REGISTRANT_NAME);

8. "Show funds with liabilities exceeding 90% of the largest liability among all funds."
WITH MaxLiability AS (
    SELECT MAX(TOTAL_LIABILITIES AS MAX_LIABILITY
    FROM FUND_REPORTED_INFO
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_LIABILITIES > 0.9 * (SELECT MAX_LIABILITY FROM MaxLiability);

9. "List funds whose net assets match their registrant's highest net asset fund."
WITH MaxNetAssets AS (
    SELECT REGISTRANT_NAME, MAX(NET_ASSETS) AS MAX_NET_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO F
JOIN REGISTRANT R ON F.ACCESSION_NUMBER = R.ACCESSION_NUMBER
WHERE NET_ASSETS = (SELECT MAX_NET_ASSETS FROM MaxNetAssets WHERE REGISTRANT_NAME = R.REGISTRANT_NAME);

10. "List registrants with above-average total assets in their state."
WITH StateAvgAssets AS (
    SELECT STATE, AVG(TOTAL_ASSETS) AS AVG_STATE_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY STATE
)
SELECT R.REGISTRANT_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.TOTAL_ASSETS > (SELECT AVG_STATE_ASSETS FROM StateAvgAssets WHERE STATE = R.STATE);

11. "Identify funds whose liabilities exceed the largest liability for any bond fund."
WITH MaxBondLiability AS (
    SELECT MAX(TOTAL_LIABILITIES) AS MAX_BOND_LIABILITY
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%BOND%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_LIABILITIES > (SELECT MAX_BOND_LIABILITY FROM MaxBondLiability);

12. "Show registrants managing the largest fund in each state."
WITH LargestFundPerState AS (
    SELECT R.STATE, MAX(F.TOTAL_ASSETS) AS MAX_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY R.STATE
)
SELECT R.REGISTRANT_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.TOTAL_ASSETS = (SELECT MAX_ASSETS FROM LargestFundPerState WHERE STATE = R.STATE);

13. "Find the smallest fund for each registrant."
WITH SmallestFunds AS (
    SELECT REGISTRANT_NAME, MIN(TOTAL_ASSETS) AS MIN_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
)
SELECT R.REGISTRANT_NAME, F.SERIES_NAME
FROM FUND_REPORTED_INFO F
JOIN REGISTRANT R ON F.ACCESSION_NUMBER = R.ACCESSION_NUMBER
WHERE F.TOTAL_ASSETS = (SELECT MIN_ASSETS FROM SmallestFunds WHERE REGISTRANT_NAME = R.REGISTRANT_NAME);

14. "List funds whose cash exceeds the average cash for their registrant."
WITH RegistrantAvgCash AS (
    SELECT REGISTRANT_NAME, AVG(CASH_NOT_RPTD_IN_C_OR_D) AS AVG_CASH
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
)
SELECT F.SERIES_NAME
FROM FUND_REPORTED_INFO F
JOIN REGISTRANT R ON F.ACCESSION_NUMBER = R.ACCESSION_NUMBER
WHERE F.CASH_NOT_RPTD_IN_C_OR_D > (SELECT AVG_CASH FROM RegistrantAvgCash WHERE REGISTRANT_NAME = R.REGISTRANT_NAME);

15. "Show states with above-average registrant counts."
WITH AvgRegistrantsPerState AS (
    SELECT AVG(REG_COUNT) AS AVG_COUNT
    FROM (SELECT STATE, COUNT(*) AS REG_COUNT FROM REGISTRANT GROUP BY STATE) Subquery
)
SELECT STATE
FROM REGISTRANT
GROUP BY STATE
HAVING COUNT(*) > (SELECT AVG_COUNT FROM AvgRegistrantsPerState);

16. "Find funds with net assets exceeding the maximum for equity funds."
WITH MaxEquityNetAssets AS (
    SELECT MAX(NET_ASSETS) AS MAX_NET_ASSETS
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%EQUITY%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE NET_ASSETS > (SELECT MAX_NET_ASSETS FROM MaxEquityNetAssets);

17. "List registrants managing the largest fund across all registrants."
WITH LargestFund AS (
    SELECT MAX(TOTAL_ASSETS) AS MAX_TOTAL_ASSETS
    FROM FUND_REPORTED_INFO
)
SELECT R.REGISTRANT_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.TOTAL_ASSETS = (SELECT MAX_TOTAL_ASSETS FROM LargestFund);

18. "Identify funds with liabilities less than the smallest liability for bond funds."
WITH MinBondLiability AS (
    SELECT MIN(TOTAL_LIABILITIES) AS MIN_BOND_LIABILITY
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%BOND%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_LIABILITIES < (SELECT MIN_BOND_LIABILITY FROM MinBondLiability);

19. "Find the largest fund in each state."
WITH StateLargestFund AS (
    SELECT STATE, MAX(TOTAL_ASSETS) AS MAX_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY STATE
)
SELECT R.STATE, F.SERIES_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.TOTAL_ASSETS = (SELECT MAX_ASSETS FROM StateLargestFund WHERE STATE = R.STATE);

20. "Show funds with a percentage of their portfolio in cash exceeding 20%."
WITH CashPercentage AS (
    SELECT SERIES_NAME, (CASH_NOT_RPTD_IN_C_OR_D / TOTAL_ASSETS) AS CASH_RATIO
    FROM FUND_REPORTED_INFO
    WHERE CASH_NOT_RPTD_IN_C_OR_D IS NOT NULL AND TOTAL_ASSETS > 0
)
SELECT SERIES_NAME
FROM CashPercentage
WHERE CASH_RATIO > 0.2;

21. "Identify funds with above-average monthly redemption flows."
WITH AvgRedemptionFlow AS (
    SELECT AVG(REDEMPTION_FLOW_MON1 + REDEMPTION_FLOW_MON2 + REDEMPTION_FLOW_MON3) AS AVG_FLOW
    FROM FUND_REPORTED_INFO
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE (REDEMPTION_FLOW_MON1 + REDEMPTION_FLOW_MON2 + REDEMPTION_FLOW_MON3) > (SELECT AVG_FLOW FROM AvgRedemptionFlow);

22. "Find registrants whose largest fund exceeds $1 billion in total assets."
WITH LargestFundPerRegistrant AS (
    SELECT REGISTRANT_NAME, MAX(TOTAL_ASSETS) AS MAX_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
)
SELECT REGISTRANT_NAME
FROM LargestFundPerRegistrant
WHERE MAX_ASSETS > 1000000000;

23. "Show funds with liabilities smaller than the smallest liability of any bond fund."
WITH MinBondFundLiability AS (
    SELECT MIN(TOTAL_LIABILITIES) AS MIN_LIABILITY
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%BOND%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_LIABILITIES < (SELECT MIN_LIABILITY FROM MinBondFundLiability);

24. "Find the total cash held by registrants whose largest fund exceeds $500 million."
WITH RegistrantsWithLargeFunds AS (
    SELECT REGISTRANT_NAME
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
    HAVING MAX(F.TOTAL_ASSETS) > 500000000
)
SELECT R.REGISTRANT_NAME, SUM(F.CASH_NOT_RPTD_IN_C_OR_D) AS TOTAL_CASH
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE R.REGISTRANT_NAME IN (SELECT REGISTRANT_NAME FROM RegistrantsWithLargeFunds)
GROUP BY R.REGISTRANT_NAME;

25. "List funds that have a greater percentage of cash compared to any equity fund."
WITH MaxEquityCashRatio AS (
    SELECT MAX(CASH_NOT_RPTD_IN_C_OR_D / TOTAL_ASSETS) AS MAX_EQUITY_CASH_RATIO
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%EQUITY%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE CASH_NOT_RPTD_IN_C_OR_D / TOTAL_ASSETS > (SELECT MAX_EQUITY_CASH_RATIO FROM MaxEquityCashRatio);

26. "Identify states with more than 10 registrants having net assets above the average."
WITH AvgNetAssets AS (
    SELECT AVG(NET_ASSETS) AS AVG_NET_ASSETS
    FROM FUND_REPORTED_INFO
)
SELECT R.STATE, COUNT(*) AS REGISTRANT_COUNT
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.NET_ASSETS > (SELECT AVG_NET_ASSETS FROM AvgNetAssets)
GROUP BY R.STATE
HAVING COUNT(*) > 10;

27. "Show registrants with the largest portfolio turnover ratio."
WITH PortfolioTurnover AS (
    SELECT REGISTRANT_NAME, 
           MAX((F.SALES_FLOW_MON1 + F.SALES_FLOW_MON2 + F.SALES_FLOW_MON3) 
               / F.TOTAL_ASSETS) AS TURNOVER_RATIO
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY REGISTRANT_NAME
)
SELECT REGISTRANT_NAME
FROM PortfolioTurnover
ORDER BY TURNOVER_RATIO DESC
LIMIT 1;

28. "Find funds whose liabilities are larger than the average liabilities of bond funds."
WITH AvgBondLiability AS (
    SELECT AVG(TOTAL_LIABILITIES) AS AVG_BOND_LIABILITY
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%BOND%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE TOTAL_LIABILITIES > (SELECT AVG_BOND_LIABILITY FROM AvgBondLiability);

29. "Identify states where the largest fund is managed by Vanguard."
WITH VanguardLargestFund AS (
    SELECT STATE, MAX(TOTAL_ASSETS) AS MAX_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    WHERE R.REGISTRANT_NAME LIKE '%VANGUARD%'
    GROUP BY STATE
)
SELECT STATE
FROM VanguardLargestFund;

30. "Find exisiting funds with the highest proportion of liabilities to net assets."
WITH LiabilityToNetAssets AS (
    SELECT SERIES_NAME, 
           (TOTAL_LIABILITIES / NET_ASSETS) AS LIABILITY_RATIO
    FROM FUND_REPORTED_INFO
    WHERE NET_ASSETS > 0
)
SELECT SERIES_NAME, LIABILITY_RATIO
FROM LiabilityToNetAssets
WHERE SERIES_NAME != 'N/A'
ORDER BY LIABILITY_RATIO DESC
LIMIT 1;

31. "Identify funds with monthly sales flows larger than any ETF."
WITH MaxETFSalesFlow AS (
    SELECT MAX(SALES_FLOW_MON1 + SALES_FLOW_MON2 + SALES_FLOW_MON3) AS MAX_ETF_FLOW
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%ETF%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE (SALES_FLOW_MON1 + SALES_FLOW_MON2 + SALES_FLOW_MON3) > (SELECT MAX_ETF_FLOW FROM MaxETFSalesFlow);

32. "Identify funds whose cash proportion is higher than the average cash proportion of equity funds."
WITH AvgEquityCashRatio AS (
    SELECT AVG(CASH_NOT_RPTD_IN_C_OR_D / TOTAL_ASSETS) AS AVG_CASH_RATIO
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%EQUITY%' AND TOTAL_ASSETS > 0
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE (CASH_NOT_RPTD_IN_C_OR_D / TOTAL_ASSETS) > (SELECT AVG_CASH_RATIO FROM AvgEquityCashRatio);

33. "Show registrants managing funds with liabilities higher than any convertible security fund."
WITH MaxConvertibleLiability AS (
    SELECT MAX(TOTAL_LIABILITIES) AS MAX_CONVERTIBLE_LIABILITY
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%CONVERTIBLE%'
)
SELECT R.REGISTRANT_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.TOTAL_LIABILITIES > (SELECT MAX_CONVERTIBLE_LIABILITY FROM MaxConvertibleLiability);

34. "List funds with monthly sales flows higher than the average for all funds."
WITH AvgSalesFlow AS (
    SELECT AVG(SALES_FLOW_MON1 + SALES_FLOW_MON2 + SALES_FLOW_MON3) AS AVG_SALES_FLOW
    FROM FUND_REPORTED_INFO
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE (SALES_FLOW_MON1 + SALES_FLOW_MON2 + SALES_FLOW_MON3) > (SELECT AVG_SALES_FLOW FROM AvgSalesFlow);

35. "Find funds with liabilities less than the average liabilities of all funds in their state."
WITH AvgStateLiability AS (
    SELECT R.STATE, AVG(F.TOTAL_LIABILITIES) AS AVG_LIABILITY
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY R.STATE
)
SELECT F.SERIES_NAME
FROM FUND_REPORTED_INFO F
JOIN REGISTRANT R ON F.ACCESSION_NUMBER = R.ACCESSION_NUMBER
WHERE F.TOTAL_LIABILITIES < (SELECT AVG_LIABILITY FROM AvgStateLiability WHERE STATE = R.STATE);

36. "Identify registrants managing funds with the highest cash proportion in their state."
WITH StateMaxCash AS (
    SELECT R.STATE, MAX(F.CASH_NOT_RPTD_IN_C_OR_D / F.TOTAL_ASSETS) AS MAX_CASH_RATIO
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    WHERE F.TOTAL_ASSETS > 0
    GROUP BY R.STATE
)
SELECT R.REGISTRANT_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.CASH_NOT_RPTD_IN_C_OR_D / F.TOTAL_ASSETS = 
      (SELECT MAX_CASH_RATIO FROM StateMaxCash WHERE STATE = R.STATE);

37. "Find states with total liabilities higher than the average liabilities for all states."
WITH AvgStateLiability AS (
    SELECT R.STATE, AVG(F.TOTAL_LIABILITIES) AS AVG_STATE_LIABILITY
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    GROUP BY R.STATE
)
SELECT STATE
FROM AvgStateLiability
WHERE AVG_STATE_LIABILITY > (SELECT AVG(AVG_STATE_LIABILITY) FROM AvgStateLiability);

38. "Show registrants managing funds with liabilities larger than the maximum liabilities of any index fund."
WITH MaxIndexFundLiability AS (
    SELECT MAX(TOTAL_LIABILITIES) AS MAX_INDEX_LIABILITY
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%INDEX%'
)
SELECT R.REGISTRANT_NAME
FROM REGISTRANT R
JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
WHERE F.TOTAL_LIABILITIES > (SELECT MAX_INDEX_LIABILITY FROM MaxIndexFundLiability);

39. "Find funds whose redemption flows exceed the highest redemption flow for any bond fund."
WITH MaxBondRedemptionFlow AS (
    SELECT MAX(REDEMPTION_FLOW_MON1 + REDEMPTION_FLOW_MON2 + REDEMPTION_FLOW_MON3) AS MAX_BOND_FLOW
    FROM FUND_REPORTED_INFO
    WHERE SERIES_NAME LIKE '%BOND%'
)
SELECT SERIES_NAME
FROM FUND_REPORTED_INFO
WHERE (REDEMPTION_FLOW_MON1 + REDEMPTION_FLOW_MON2 + REDEMPTION_FLOW_MON3) > (SELECT MAX_BOND_FLOW FROM MaxBondRedemptionFlow);

40. "List states with the highest average net assets per fund."
WITH StateAvgNetAssets AS (
    SELECT R.STATE, AVG(F.NET_ASSETS) AS AVG_NET_ASSETS
    FROM REGISTRANT R
    JOIN FUND_REPORTED_INFO F ON R.ACCESSION_NUMBER = F.ACCESSION_NUMBER
    WHERE F.NET_ASSETS IS NOT NULL
    GROUP BY R.STATE
)
SELECT STATE
FROM StateAvgNetAssets
WHERE AVG_NET_ASSETS = (SELECT MAX(AVG_NET_ASSETS) FROM StateAvgNetAssets);
```
"""
